---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/members":
    get:
      summary: Retrieve all members
      tags:
      - Members
      responses:
        '200':
          description: Return information based on query
    post:
      summary: Creates a member
      tags:
      - Members
      parameters: []
      responses:
        '200':
          description: Created contact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                city:
                  type: string
                state:
                  type: string
                country:
                  type: string
                team_id:
                  type: integer
  "/api/v1/members/{id}":
    get:
      summary: Retrieves a member
      tags:
      - Members
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: member found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
    put:
      summary: Update member
      tags:
      - Members
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Updated member
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                city:
                  type: string
                state:
                  type: string
                country:
                  type: string
                team_id:
                  type: integer
    delete:
      summary: Delete a member
      tags:
      - Members
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Return member deleted
  "/api/v1/projects":
    get:
      summary: Retrieve all projects
      tags:
      - Projects
      responses:
        '200':
          description: Return information based on query
    post:
      summary: Creates a project
      tags:
      - Projects
      parameters: []
      responses:
        '200':
          description: Created contact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  "/api/v1/projects/{id}":
    get:
      summary: Retrieves a project
      tags:
      - Projects
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: project found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
    put:
      summary: Update project
      tags:
      - Projects
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Updated project
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    delete:
      summary: Delete a project
      tags:
      - Projects
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Return project deleted
  "/api/v1/teams":
    get:
      summary: Retrieve all teams
      tags:
      - Teams
      responses:
        '200':
          description: Return information based on query
    post:
      summary: Creates a team
      tags:
      - Teams
      parameters: []
      responses:
        '200':
          description: Created contact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  "/api/v1/teams/{id}":
    get:
      summary: Retrieves a team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: team found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
    put:
      summary: Update team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Updated Team
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    delete:
      summary: Delete a Team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Return team deleted
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: http://127.0.0.1:3000
