---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/teams":
    get:
      summary: Retrieve all teams
      tags:
      - Teams
      responses:
        '200':
          description: Return information based on query
    post:
      summary: Creates a team
      tags:
      - Teams
      parameters: []
      responses:
        '200':
          description: Created contact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
  "/api/v1/teams/{id}":
    get:
      summary: Retrieves a team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: team found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                required:
                - id
    put:
      summary: Update team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Updated Team
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
    delete:
      summary: Delete a Team
      tags:
      - Teams
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: Return team deleted
servers:
- url: http://127.0.0.1:3000
  variables:
    defaultHost:
      default: http://127.0.0.1:3000
